// Turns StudioExport/manifest.json into StudioExport/Studio/Modules/UILayout.lua (a Luau ModuleScript source),
// so Studio can read the layout without HttpService.
// Usage: node tools/studio/make_layout.js [exportDir]   (default: StudioExport)
const fs = require('fs');
const path = require('path');
const dir = path.resolve(process.argv[2] || 'StudioExport');
const m = JSON.parse(fs.readFileSync(path.join(dir, 'manifest.json'), 'utf8'));

const lua = v => {
  if (v === null || v === undefined) return 'nil';
  if (typeof v === 'boolean' || typeof v === 'number') return String(v);
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) return '{' + v.map(lua).join(', ') + '}';
  return '{' + Object.entries(v).filter(([, x]) => x !== null && x !== undefined && x !== false)
    .map(([k, x]) => `${/^[A-Za-z_]\w*$/.test(k) ? k : `[${JSON.stringify(k)}]`} = ${lua(x)}`).join(', ') + '}';
};
// the same image placed twice in one spot (a shared icon that also has a screen-specific export):
// keep the first, more specific one
const taken = [];
for (const a of m.assets) {
  a.instances = a.instances.filter(i => {
    const dup = taken.some(t => t.screen === i.screen && Math.abs(t.x - i.x) <= 3 && Math.abs(t.y - i.y) <= 3 && Math.abs(t.w - i.w) <= 6 && Math.abs(t.h - i.h) <= 6);
    if (!dup) taken.push(i);
    return !dup;
  });
}
fs.writeFileSync(path.join(dir, 'manifest.json'), JSON.stringify(m, null, 1));
const key = f => f.replace(/^Assets\//, '').replace(/\.png$/, '');

let s = `-- Build a Terrarium UI layout (generated by tools/studio/make_layout.js; do not edit by hand)
-- Coordinates are pixels on a 1920 x 1080 design canvas. Each asset lists every place it is used.
local Layout = {}
Layout.canvas = ${lua(m.canvas)}
Layout.screens = ${lua(m.screens)}
Layout.assets = {
`;
for (const a of m.assets) {
  s += '  ' + lua({ key: key(a.file), name: a.name, size: a.size, pixels: a.pixels, button: a.button, baked: a.baked, spin: a.spin,
    fill: a.fill, leftFill: a.leftFill, vineSet: a.vineSet, front: a.front, slice: a.slice, tile: a.tile,
    instances: a.instances.map(i => ({ screen: i.screen, x: i.x, y: i.y, w: i.w, h: i.h, alt: i.alt })) }) + ',\n';
}
s += '}\nLayout.texts = {\n';
for (const t of m.texts) s += '  ' + lua(t) + ',\n';
s += '}\nLayout.slots = {\n';
for (const t of m.slots) s += '  ' + lua(t) + ',\n';
s += '}\nLayout.frames = {\n';
for (const t of m.frames) s += '  ' + lua(t) + ',\n';
s += '}\nreturn Layout\n';

const out = path.join(dir, 'Studio', 'Modules');
fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(path.join(out, 'UILayout.lua'), s);
// asset key list, used by the uploader and as the AssetIds template
const keys = m.assets.map(a => key(a.file));
fs.writeFileSync(path.join(out, 'AssetIds.lua'), '-- Filled in by upload_assets.py and ResolveImageIds.lua. Key = file path inside Assets/ without .png\nreturn {\n' +
  keys.map(k => `  [${JSON.stringify(k)}] = "", -- rbxassetid://...`).join('\n') + '\n}\n');
console.log(`UILayout.lua: ${m.assets.length} assets, ${m.texts.length} texts, ${m.slots.length} slots, ${m.frames.length} frames`);
